// Saves generated bytes (e.g. an .xlsx export) to the user's device: a browser
// download on web, the system "save file" dialog on Android/desktop.
export 'file_download_io.dart' if (dart.library.js_interop) 'file_download_web.dart';
